apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jfrog-nginx
  namespace: argocd
spec:
  destination:
  #  name: ''
    namespace: kaaaaaj
    server: 'https://kubernetes.default.svc'
  source:
    path: .
    repoURL: 'https://github.com/dinkol/nginx-aks-deployment.git'
    targetRevision: jfrog
#  sources: []
  project: dinko
  syncPolicy:
    automated:
  #    prune: false
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
