apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: testmginx
spec:
  destination:
    name: ''
    namespace: production
    server: 'https://kubernetes.default.svc'
  source:
    path: 'nginx-aks-deployment '
    repoURL: 'https://github.com/dinkol/nginx-aks-deployment.git'
    targetRevision: HEAD
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
