apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jfrognewns-nginx
spec:
  destination:
    name: ''
    namespace: jfrognewns
    server: 'https://kubernetes.default.svc'
  source:
    path: .
    repoURL: 'https://github.com/dinkol/nginx-aks-deployment.git'
    targetRevision: jfrognewns
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
