apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginxapp
spec:
  destination:
    name: ''
    namespace: production
    server: 'https://aks-aks-rg-7fa599-4ymck29s.hcp.westeurope.azmk8s.io'
  source:
    path: 'nginx-aks-deployment '
    repoURL: 'https://github.com/dinkol/nginx-aks-deployment.git'
    targetRevision: HEAD
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
