apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jfrog-nginx
  namespace: kaaaaaj
spec:
  destination:
    name: ''
    namespace: default
    server: 'https://kubernetes.default.svc'
  source:
    path: .
    repoURL: 'https://github.com/dinkol/nginx-aks-deployment.git'
    targetRevision: jfrog
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
  syncOptions:
  - CreateNamespace=true
