apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: testguide
spec:
  destination:
    name: ''
    namespace: testguide
    server: 'https://kubernetes.default.svc'
  source:
    path: .
    repoURL: 'https://github.com/dinkol/nginx-aks-deployment.git'
    targetRevision: testguide
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
