apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: argocd-namespace-manager-binding
subjects:
- kind: ServiceAccount
  name: argocd-server # Replace with the actual name of Argo CD's service account
  namespace: argocd # Replace with the namespace where Argo CD is installed
roleRef:
  kind: ClusterRole
  name: argocd-namespace-manager
  apiGroup: rbac.authorization.k8s.io
