apiVersion: apps/v1
kind: Deployment
metadata:
  name: jfrognewns-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jfrognewns-nginx
  template:
    metadata:
      labels:
        app: jfrognewns-nginx
    spec:
      containers:
      - name: jfrognewns-nginx
        image: autojfrog.jfrog.io/docker-trial/mynginximage:latest 
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "200m"
          limits:
            memory: "128Mi"
            cpu: "330m"
      imagePullSecrets:
      - name: jfrogaks-registry-credentials
