apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-staging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-staging
  template:
    metadata:
      labels:
        app: nginx-staging
    spec:
      containers:
      - name: nginx-staging
        image: nginx
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "300m"
          limits:
            memory: "128Mi"
            cpu: "250m"
