apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-realtest
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-realtest
  template:
    metadata:
      labels:
        app: nginx-realtest
    spec:
      containers:
      - name: nginx-realtest
        image: nginx
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "55Mi"
            cpu: "150m"
          limits:
            memory: "128Mi"
            cpu: "250m"
        nodeSelector:
          agentpool: ngnixnp
