apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-qa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-qa
  template:
    metadata:
      labels:
        app: nginx-qa
    spec:
      containers:
      - name: nginx-qa
        image: nginx
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "74Mi"
            cpu: "200m"
          limits:
            memory: "128Mi"
            cpu: "250m"
