name: Database Backup

on:
 
  workflow_dispatch:

jobs:
  backup:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

#    - name: Install PostgreSQL client
#      run: |
#        sudo apt-get update
#        sudo apt-get install -y postgresql-client

    - name: Run pg_dump
      env:
        PGPASSWORD: ${{ secrets.DB_PASSWORD }}
      run: |
        pg_dump -U ${{ secrets.DB_USER }} -h ${{ secrets.DB_HOST }} -p ${{ secrets.DB_PORT }} ${{ secrets.DB_NAME }} > db_backup.sql
        
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: |
          {
            "clientId": "${{ secrets.AZURE_CLIENT_ID }}",
            "clientSecret": "${{ secrets.AZURE_CLIENT_SECRET }}",
            "subscriptionId": "${{ secrets.AZURE_SUBSCRIPTION_ID }}",
            "tenantId": "${{ secrets.AZURE_TENANT_ID }}"
          }
          
    - name: Set AKS Context
      uses: azure/aks-set-context@v1
      with:
        creds: |
          {
            "clientId": "${{ secrets.AZURE_CLIENT_ID }}",
            "clientSecret": "${{ secrets.AZURE_CLIENT_SECRET }}",
            "subscriptionId": "${{ secrets.AZURE_SUBSCRIPTION_ID }}",
            "tenantId": "${{ secrets.AZURE_TENANT_ID }}"
          }
        cluster-name: aks
        resource-group: aks-rg
          
    - name: Upload file to Azure Blob Storage
      run: |       
        STORAGE_ACCOUNT_NAME="postgresqlsatest"
        CONTAINER_NAME="backupcontainer"
        LOCAL_FILE_PATH="db_backup.sql"
        BLOB_NAME="db_backup.sql"

        # Install Azure CLI extension for Blob Storage
        az extension add --name storage-preview

        # Upload the file
        az storage blob upload \
          --account-name $STORAGE_ACCOUNT_NAME \
          --container-name $CONTAINER_NAME \
          --name $BLOB_NAME \
          --file $LOCAL_FILE_PATH \
          --auth-mode login
      env:
        AZURE_STORAGE_ACCOUNT: ${{ secrets.STORAGE_ACCOUNT }}
        AZURE_STORAGE_KEY: ${{ secrets.STORAGE_KEY }}

    - name: Logout from Azure
      run: az logout
