name: Create Kubernetes Namespace

on:
  push:
    branches:
      - dev  # Trigger the workflow on push to the main branch

jobs:
  create-namespace:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Install kubectl
      run: |
        curl -LO "https://storage.googleapis.com/kubernetes-release/release/`curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt`/bin/linux/amd64/kubectl"
        chmod +x ./kubectl
        sudo mv ./kubectl /usr/local/bin/kubectl

    - name: Set up Kubeconfig
      run: |
        echo "${{ secrets.KUBE_CONFIG }}" | base64 -d > ./kubeconfig
        export KUBECONFIG=./kubeconfig

    - name: Create Namespace
      run: |
        curl -s https://raw.githubusercontent.com/dinkol/nginx-aks-deployment/feature1dev/namespace.sh | bash

  lint:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Super-Linter
  # You may pin to the exact commit or the version.
  # uses: super-linter/super-linter@a8150b40c89574adb5f68bf9502b890a236a06b3
        uses: super-linter/super-linter@v5.7.2
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN}}
          
    
