name: Database restore

on:
  workflow_dispatch:

jobs:
  restore-database:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Download PostgreSQL client
      run: |
        sudo sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt/ $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list'
        wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -

    - name: Install PostgreSQL client
      run: |
        sudo apt-get update
        sudo apt-get install -y postgresql-client-15

    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS_BLOBUPLOADSP }}

    - name: Download .sql file from Azure Blob Storage
      run: |
        az storage blob download \
          --account-name postgresqlsatest \
          --container-name backupcontainer \
          --name db_backup1.sql \
          --file db_backup1.sql \
          --auth-mode login

    - name: Restore Database from .sql file
      run: |
        PGPASSWORD=${{ secrets.POSTGRES_PASSWORD }} 
            psql -h ${{ secrets.DB_HOST }} -U ${{ secrets.POSTGRES_USER }} -d ${{ secrets.POSTGRES_DB }} -f db_backup1.sql
        
      env:
        PGPASSWORD: ${{ secrets.POSTGRES_PASSWORD }}

    - name: Logout from Azure
      run: az logout

