name: Lint

on:  # yamllint disable-line rule:truthy
  push: null
  pull_request: null

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: [ ubuntu-latest]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set GITHUB_BEFORE_SHA
        id: set_before_sha
        run: |
          if git rev-parse HEAD~1 > /dev/null 2>&1; then
            echo "Setting GITHUB_BEFORE_SHA to the previous commit SHA"
            echo "GITHUB_BEFORE_SHA=$(git rev-parse HEAD~1)" >> $GITHUB_ENV
          else
            echo "Repository does not have a previous commit. Using current HEAD as GITHUB_BEFORE_SHA"
            echo "GITHUB_BEFORE_SHA=$(git rev-parse HEAD)" >> $GITHUB_ENV
          fi

      - name: Use GITHUB_BEFORE_SHA
        run: |
          echo "GITHUB_BEFORE_SHA is set to $GITHUB_BEFORE_SHA"
          
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      - name: Run Local Super-Linter
  # You may pin to the exact commit or the version.
  # uses: super-linter/super-linter@a8150b40c89574adb5f68bf9502b890a236a06b3
        uses: ./.github/actions/super-linter-main
        env:
          VALIDATE_YAML: true
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN}}